const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // Deploy RewardToken
  const RewardToken = await hre.ethers.getContractFactory("RewardToken");
  const rewardToken = await RewardToken.deploy(deployer.address);
  await rewardToken.deployed();
  console.log("RewardToken deployed at:", rewardToken.address);

  // Deploy NotesStorage
  const NotesStorage = await hre.ethers.getContractFactory("NotesStorage");
  const notesStorage = await NotesStorage.deploy(rewardToken.address);
  await notesStorage.deployed();
  console.log("NotesStorage deployed at:", notesStorage.address);

  // Set NotesStorage as a minter automatically!
  console.log("Setting NotesStorage as an authorized minter...");
  const tx = await rewardToken.setMinter(notesStorage.address, true);
  await tx.wait();
  console.log("Minter permissions set.");

  // Write addresses directly into the frontend React app automatically
  const configPath = path.join(__dirname, "..", "frontend", "src", "contracts", "contractConfig.js");
  const configContent = `// Auto-generated by deploy.js
export const NOTES_ADDRESS = "${notesStorage.address}";
export const TOKEN_ADDRESS = "${rewardToken.address}";
`;

  fs.writeFileSync(configPath, configContent);
  console.log("Updated frontend contractConfig.js addresses automagically!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
